<?php
$z[0]=Array("field","",15,44);
$z[0][4]['name']="typename";
$z[1]=Array("field","",52,80);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",83,112);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n                        <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n                        ",190,379);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>