<h3><a  title="{dede:field name='typename'/}" href="{dede:field name='typeurl'/}" >{dede:field name='typename'/}</a></h3>
                    <ul class="clearfix">
                        {dede:channel type='son' noself='yes'}
                        <li><a href="[field:typelink/]" title="[field:typename/]">[field:typename/]</a></li>
                        {/dede:channel}
                    </ul>