<?php
$z[0]=Array("arcurl","",56,71);
$z[1]=Array("litpic","",136,151);
$z[2]=Array("fulltitle","",167,185);
$z[3]=Array("fulltitle","",194,212);
$z[4]=Array("fulltitle","",301,319);
$z[5]=Array("arcurl","",327,342);
$z[6]=Array("title","",355,369);
$z[7]=Array("info","",418,431);
$z[8]=Array("body","",495,549);
$z[8][4]['function']="cn_substr(html2text(@me),180)";
$z[9]=Array("fulltitle","",595,613);
$z[10]=Array("arcurl","",621,636);

?>