<div class="l2tit" style="width: 95%;">  
						[<a title="[field:typename/]" target="_blank" href="[field:typeurl/]">[field:typename/]</a>]
                        <a title="[field:title/]" href="[field:arcurl/]" target="_blank" class="f14">[field:title/]</a>
						<span class="f11">[ [field:stime/] ]</span>	
					</div>
                    <div class="clear">
                    </div>
					<dl class="sear_dl">
						<dt class="dt2">
							<a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]">
								<img src="[field:litpic/]" title="[field:fulltitle/]" alt="[field:fulltitle/]" /></a>
						</dt>
						<dd class="d2">
							[field:description/]…
							<a href="[field:arcurl/]" class="cRed" title="[field:fulltitle/]">[查看]</a>
						</dd>
                        <dd>
							<a href="[field:arcurl/]" class="a_d" title="[field:fulltitle/]">
                             [field:global.cfg_basehost/][field:arcurl/]</a>
							 <img src="[field:global.cfg_templets_skin/]/Images/Index/x3.gif" alt="3星" class="vam" />
						</dd>
					</dl>