<dl class="pj_list_dl">
						<dt><a target="_blank" href="[field:arcurl/]">
                                <img src="[field:litpic/]" alt="[field:fulltitle/]"
                                    title="[field:fulltitle/]" /></a>
						</dt>
                        <dd>
                            <a href="[field:arcurl/]" target="_blank"
                                    title="[field:fulltitle/]">
                                    [field:fulltitle/]</a>
						</dd>
					</dl>