<dt><a target="_blank" href="[field:arcurl /]" title="[field:fulltitle/]">
                        <img class="classname" src="[field:litpic/]"
                        alt="[field:fulltitle/]" title="[field:fulltitle/]" /></a>
                    </dt>
                    <dd>
                        <ul class="clearfix">
                            [field:id function="Getimgs(@me,210,164,4)" /]
                        </ul>
                    </dd>