<?php
$z[0]=Array("arcurl","",42,57);
$z[1]=Array("litpic","",122,137);
$z[2]=Array("fulltitle","",153,171);
$z[3]=Array("fulltitle","",180,198);
$z[4]=Array("fulltitle","",256,274);
$z[5]=Array("arcurl","",282,297);
$z[6]=Array("title","",310,324);
$z[7]=Array("info","",356,369);
$z[8]=Array("body","",396,450);
$z[8][4]['function']="cn_substr(html2text(@me),180)";
$z[9]=Array("fulltitle","",479,497);
$z[10]=Array("arcurl","",505,520);

?>