<dl class="clearfix">
						<dt><a href="[field:arcurl/]">
							<img class="classname" style="display: inline;" _src="[field:litpic/]"
								alt="[field:fulltitle/]" title="[field:fulltitle/]" /></a></dt>
						<dd>
							<h6>
								<a title="[field:fulltitle/]" href="[field:arcurl/]">
									[field:title/]</a></h6>
							<em>
								[field:info/]</em>
							<p>
								[field:body function='cn_substr(html2text(@me),180)'/]</p>
							<span><a title="[field:fulltitle/]" href="[field:arcurl/]">
								[查看详情] </a></span>
						</dd>
					</dl>