<?php
$z[0]=Array("arclist","\r\n			<td><a href=\"[field:arcurl /]\"><img width=\"200\" height=\"130\" src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" /></a></td>\r\n						\r\n		",1431,1654);
$z[0][4]['row']="3";
$z[0][4]['titlelen']="24";
$z[0][4]['orderby']="pubdate";
$z[0][4]['idlist']="90,59,58";
$z[1]=Array("arclist","\r\n			<td><a href=\"[field:arcurl /]\"><img width=\"200\" height=\"130\" src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" /></a></td>\r\n		",1675,1890);
$z[1][4]['row']="3";
$z[1][4]['titlelen']="24";
$z[1][4]['orderby']="pubdate";
$z[1][4]['idlist']="57,55,52";

?>