{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='0' row='2' col='2' value='3'/}
{dede:img ddimg='' text='郑州商场超市保洁方案,郑州商场保洁,郑州超市保洁' width='187' height='114'} /uploads/allimg/141223/1-141223112P9.jpg {/dede:img}
{dede:img ddimg='' text='郑州商场超市保洁方案,郑州商场保洁,郑州超市保洁' width='187' height='114'} /uploads/allimg/141223/1-141223112Q0.jpg {/dede:img}
{dede:img ddimg='' text='郑州商场超市保洁方案,郑州商场保洁,郑州超市保洁' width='187' height='114'} /uploads/allimg/141223/1-141223112Q2.jpg {/dede:img}
{dede:img ddimg='' text='郑州商场超市保洁方案,郑州商场保洁,郑州超市保洁' width='460' height='345'} /uploads/allimg/141223/1-141223113152.jpg {/dede:img}
