<dl class="pd_t05_con_dl">
							<dt><a href="[field:arcurl/]" target="_blank"
								title="[field:fulltitle/]">
								<img src="[field:litpic/]" alt="[field:title function='htmlspecialchars(@me)'/]"
									title="[field:fulltitle/]" /></a></dt>
								<dd>
									<a href="[field:arcurl/]" title="[field:title/]"
										target="_blank">
										[field:title/]</a></dd>
						</dl>