<li><a title="[field:fulltitle/]" href="[field:typeurl/]">
                                [[field:typename/]]</a><a href="[field:arcurl/]"
                                    target="_blank" title="[field:fulltitle/]">[field:fulltitle/]</a><span class="last">[
                                        [field:pubdate function="GetDateTimeMK(@me)"/]
                                        ]</span></li>