<div class="leib3 mt10">
	<div class="tit">联系开祥</div>
    <div class="nr">
		<img src="{dede:global.cfg_basehost/}/assets/img/index/leftlx.gif" alt="联系郑州保洁公司"
                    title="联系郑州保洁公司">
        <h5 >郑州开祥清洁服务有限公司</h5>	<br>
        <p><span>服务热线：</span>133-8382-9505	</p>
		<p><span>公司电话：</span>0371-66398288</p>
		<p><span>公司传真：</span>0371-66398288</p>
		<p><span>公司邮箱：</span>zzkxqj@126.com</p>
        <p><span>公司地址：</span>郑州市管城区商城东路20号<br></p>
	</div>
</div>