<dl class="pd_list_dl">
                        <dt><a target="_blank" href="[field:arcurl/]" title="[field:fulltitle/]">
                            <img src="[field:litpic/]" alt="[field:fulltitle/]" title="[field:fulltitle/]" /></a></dt>
                            <dd>
                                <a target="_blank" href="[field:arcurl/]" title="[field:fulltitle/]">
                                    [field:title/]</a></dd>
                    </dl>