<dl class="dl_2">
                                <dt><a title="[field:fulltitle/]" href="[field:arcurl/]" target="_blank">
                                    <img src="[field:litpic/]"
                                      title="[field:fulltitle/]" alt="[field:fulltitle/]" /></a></dt>
                                <dd>
                                    <a title="[field:fulltitle/]" href="[field:arcurl/]" target="_blank">
                                        [field:fulltitle/]</a></dd>
                            </dl>