<?php
$z[0]=Array("typename","",32,49);
$z[1]=Array("typeurl","",57,73);
$z[2]=Array("typename","",93,110);
$z[3]=Array("typename","",142,159);
$z[4]=Array("typeurl","",167,183);
$z[5]=Array("litpic","",376,391);
$z[6]=Array("arcurl","",536,551);
$z[7]=Array("title","",579,593);
$z[8]=Array("body","",685,739);
$z[8][4]['function']="cn_substr(html2text(@me),520)";
$z[9]=Array("arcurl","",808,823);

?>