<h3>
            <em><a title="[field:typename/]" href="[field:typeurl/]">
                [field:typename/]</a>/ About us</em><b><a title="[field:typename/]" href="[field:typeurl/]">+
                    more</a></b></h3>
                <dl class="clearfix">
                    <dt>
                        <div class="tc mt5">
                            <img src="[field:litpic/]" /></div>
                    </dt>
                    <dd>
                        <h6>
                    <a title="开祥简介" href="[field:arcurl/]">
                        [field:title/]</a></h6>
                        <p style="text-indent:2em">
                            [field:body function='cn_substr(html2text(@me),520)'/]...</p>
                        <span><a title="开祥简介" href="[field:arcurl/]">
                    [查看详情]</a></span>
                    </dd>
                </dl>