{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='2' col='2' value='3'/}
{dede:img ddimg='' text='医院保洁成功案例-日常保洁' width='600' height='402'} /uploads/allimg/150105/1-1501050J948.jpg {/dede:img}
{dede:img ddimg='' text='医院保洁成功案例-地面保洁1' width='600' height='399'} /uploads/allimg/150105/1-1501050K002.jpg {/dede:img}
{dede:img ddimg='' text='医院保洁成功案例-地毯清洗' width='600' height='402'} /uploads/allimg/150105/1-1501050K005.jpg {/dede:img}
{dede:img ddimg='' text='医院保洁成功案例-地面保洁2' width='600' height='399'} /uploads/allimg/150105/1-1501050K015.jpg {/dede:img}
