<?php
$z[0]=Array("global","@me=@me-1;",55,120);
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arclist","\r\n                    <dt><a target=\"_blank\" href=\"[field:arcurl /]\" title=\"[field:fulltitle/]\">\r\n                        <img class=\"classname\" src=\"[field:litpic/]\"\r\n                        alt=\"[field:fulltitle/]\" title=\"[field:fulltitle/]\" /></a>\r\n                    </dt>\r\n                    <dd>\r\n                        <ul class=\"clearfix\">\r\n                            [field:id function=\"Getimgs(@me,210,164,4)\" /]\r\n                        </ul>\r\n                    </dd>\r\n                    ",183,740);
$z[1][4]['titlelen']="42";
$z[1][4]['row']="1";

?>