<?php
$z[0]=Array("global","@me=@me-1;",55,120);
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arclist","\r\n                    <dt><a target=\"_blank\" href=\"[field:arcurl /]\"\r\n                        title=\"[field:fulltitle/]\">\r\n                        <img class=\"classname\" src=\"[field:litpic/]\"\r\n                        alt=\"[field:fulltitle/]\" title=\"[field:fulltitle/]\" /></a>\r\n\r\n					</dt>\r\n				\r\n					<dd>\r\n					<ul class=\"clearfix\">\r\n						[field:id function=\"Getimgs(@me,210,164,4)\" /] 				 \r\n\r\n					</ul>\r\n\r\n                    </dd>\r\n				",183,677);
$z[1][4]['titlelen']="42";
$z[1][4]['row']="1";

?>