<div class="sample_cont" style="display: none;" id="shk{dede:global name=itemindex runphp='yes'}@me=@me-1;{/dede:global}">                
                <dl class="clearfix">
				{dede:arclist titlelen='42' row='1'}
                    <dt><a target="_blank" href="[field:arcurl /]"
                        title="[field:fulltitle/]">
                        <img class="classname" src="[field:litpic/]"
                        alt="[field:fulltitle/]" title="[field:fulltitle/]" /></a>

					</dt>
				
					<dd>
					<ul class="clearfix">
						[field:id function="Getimgs(@me,210,164,4)" /] 				 

					</ul>

                    </dd>
				{/dede:arclist}	
                </dl>
                    
            </div>