<dl class="sear_dl" style="width: 95%;">
                                <dt class="tit"><a title="[field:typename /]" target="_blank" href="[field:typeurl/]">
                                    [[field:typename /]]</a><a target="_blank" href="[field:arcurl/]"
                                        class="f14" title="[field:fulltitle/]">[field:title/]</a><span class="f11">[
                                            [field:pubdate function="GetDateTimeMK(@me)"/]
                                            ]</span></dt>
                                <dd class="d1">
                                    [field:description/]...
								</dd>
                                <dd>
                                    <a href="[field:arcurl/]" target="_blank"
                                        class="a_d" title="[field:fulltitle/]">                                       [field:global.cfg_basehost/][field:arcurl/]</a><img src="[field:global.cfg_templets_skin/]/Images/Index/x3.gif"
                                            alt="3星" class="vam" /></dd>
                            </dl>