<?php
$z[0]=Array("global","",101,126);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",136,164);
$z[1][4]['name']="cfg_indexname";
$z[2]=Array("global","",166,194);
$z[2][4]['name']="cfg_indexname";
$z[3]=Array("channelartlist","\r\n		<a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a><span>|</span>\r\n 		",203,412);
$z[3][4]['typeid']="11,58,2,21,34,66,64,87";
$z[4]=Array("global","",720,747);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",992,1016);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",1302,1323);
$z[6][4]['name']="tongji";
$z[7]=Array("global","",1389,1410);
$z[7][4]['name']="cfg_py";
$z[8]=Array("global","",1475,1502);
$z[8][4]['name']="cfg_basehost";
$z[9]=Array("global","",1627,1654);
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("global","",1924,1951);
$z[10][4]['name']="cfg_basehost";
$z[11]=Array("global","",2399,2426);
$z[11][4]['name']="cfg_basehost";

?>