<?php
$z[0]=Array("channel","\r\n                <a href=\"[field:typeurl/]\"\r\n                    title=\"[field:typename/]\">[field:typename/]</a>|  \r\n				",341,528);
$z[0][4]['type']="self";
$z[0][4]['row']="2";
$z[0][4]['typeid']="71,59";
$z[1]=Array("global","",814,841);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",906,933);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",933,962);
$z[3][4]['name']="cfg_medias_dir";
$z[4]=Array("global","",1475,1500);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",1510,1538);
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("global","",1540,1568);
$z[6][4]['name']="cfg_indexname";
$z[7]=Array("channel","	\r\n		<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n    ",1580,1819);
$z[7][4]['type']="son";
$z[7][4]['row']="8";
$z[7][4]['typeid']="1";
$z[7][4]['currentstyle']="<li><a href=";
$z[7][4]['~typelink~" title']="[field:typename/]";
$z[7][4]['>~typename~</a></li>"']="";

?>