<?php
$z[0]=Array("channel","\r\n					<a href=\"[field:typeurl/]\"\r\n						title=\"[field:typename/]\">[field:typename/]</a>|  \r\n					",320,483);
$z[0][4]['type']="self";
$z[0][4]['row']="2";
$z[0][4]['typeid']="71,59";
$z[1]=Array("global","",719,746);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",755,783);
$z[2][4]['name']="cfg_indexname";
$z[3]=Array("global","",804,831);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",831,860);
$z[4][4]['name']="cfg_medias_dir";
$z[5]=Array("global","",899,927);
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("global","",936,962);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",1271,1296);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("global","",1306,1334);
$z[8][4]['name']="cfg_indexname";
$z[9]=Array("global","",1336,1364);
$z[9][4]['name']="cfg_indexname";
$z[10]=Array("channel","	\r\n		<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n    ",1376,1615);
$z[10][4]['type']="son";
$z[10][4]['row']="8";
$z[10][4]['typeid']="1";
$z[10][4]['currentstyle']="<li><a href=";
$z[10][4]['~typelink~" title']="[field:typename/]";
$z[10][4]['>~typename~</a></li>"']="";
$z[11]=Array("tag","\r\n					<a href='/tags.php?/[field:tag /]' target=\"_parent\" title=\"[field:tag /]\">[field:tag /]</a>\r\n					",1842,1999);
$z[11][4]['row']="6";
$z[11][4]['getall']="1";
$z[11][4]['sort']="rand";
$z[12]=Array("global","",2359,2386);
$z[12][4]['name']="cfg_basehost";

?>